site_name: Kinnari's Site
site_author: Kinnari
site_url: https://kinnariyamamatanha.github.io
site_description: Kinnari 的个人网站
repo_url: https://github.com/KinnariyaMamaTanha/kinnariyamamatanha.github.io/
repo_name: Kinnari's Site
copyright: Copyright &copy; 2024 - Present <a href="https://github.com/KinnariyaMamaTanha/" target="_blank" rel="noopener">Kinnari</a>

theme:
  name: material
  language: en
  custom_dir: overrides

  features:
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.footnote.tooltips
    - content.tabs.link
    - header.autohide
    # - navigation.instant.progress
    # - navigation.instant.prefetch
    # - navigation.instant.preview
    - navigation.tracking
    - navigation.tabs
    - navigation.top
    - navigation.path
    # - navigation.prune
    - navigation.indexes
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default # 日间模式
      primary: white # 上方的
      accent: indigo # 链接等可交互元件的高亮色
      toggle:
        icon: material/brightness-7 # 图标
        name: light mode # 鼠标悬浮提示
    - media: "(prefers-color-scheme: dark)"
      scheme: slate # 夜间模式
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: dark mode

  font:
    text: JetBrains Mono

  favicon: img/avatar1.png

  icon:
    logo: material/coffee
    repo: fontawesome/brands/git-alt
    edit: material/pencil

  static_templates:
    - 404.html

plugins:
  - callouts
  - glightbox:
      width: 80%
  - git-revision-date-localized:
      type: datetime
      timezone: Asia/Shanghai
      enable_creation_date: true
      exclude:
        - index.md
        - academy.md
        - links.md
        - changelog.md
  - minify:
      minify_html: true
  - search
  - statistics:
      words_per_minute: 200

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - footnotes
  - meta
  - md_in_html
  - nl2br
  - pymdownx.arithmatex: # latex支持
      generic: true
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.highlight: # 代码块高亮
      anchor_linenums: true
      auto_title: true # 显示编程语言名称
      linenums: true # 显示行号
      linenums_style: pymdownx-inline
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.magiclink
  - pymdownx.saneheaders
  - pymdownx.snippets
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tilde
  - sane_lists
  - tables
  - toc:
      permalink: true
      toc_depth: 4

extra_javascript:
  - https://cn.vercount.one/js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  # - https://busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js
  # - https://busuanzi.icodeq.com/busuanzi.pure.mini.js
  - js/mathjax.js
  # - js/toc.js

extra_css:
  - css/custom.css
  - https://gcore.jsdelivr.net/npm/lxgw-wenkai-screen-webfont@1.1.0/style.css
  - https://gcore.jsdelivr.net/npm/lxgw-wenkai-webfont@1.1.0/style.css
  # - css/fold_toc.css
  - css/card.css
  - css/flink.css
  - css/tasklist.css

extra:
  social:
    - icon: /fontawesome/brands/github
      link: https://github.com/kinnariyamamatanha/
      name: GitHub
    - icon: /fontawesome/brands/qq
      link: /img/qq.jpg
      name: 加加我的QQ
    - icon: /fontawesome/brands/weixin
      link: /img/wechat.jpg
      name: 加加我的微信
    - icon: /fontawesome/brands/x-twitter
      link: https://x.com/MamaTanha76294
      name: X
    - icon: /fontawesome/brands/zhihu
      link: https://www.zhihu.com/people/Kinnariya
      name: Zhihu
    - icon: fontawesome/solid/paper-plane
      link: mailto:2823324228@qq.com
      name: send email to me!

  analytics:
    provider: google
    property: G-20LWGZNLLR
    feedback:
      title: Support Me!
      ratings:
        - icon: fontawesome/regular/hand-back-fist
          name: Support Me!
          data: 1
          note: >-
            <center> 难道说……你愿意给我买一瓶快乐水吗！🫣 </center>
            <center> How about...buy me a coffee？😋 </center>
            <img src="https://cdn.jsdelivr.net/gh/KinnariyaMamaTanha/Images@images/%E5%BE%AE%E4%BF%A1%E5%9B%BE%E7%89%87_2024-12-07_230055_143.png" width=200px>

nav:
  - Home: index.md
  - Notes:
      - index: notes/index.md
      - CS61C:
          - "1 Intro": notes/cs61c/1-intro.md
          - "2 C Intro": notes/cs61c/2-c-intro.md
          - "3 Floating Point": notes/cs61c/3-floating-point.md
          - "4 RISC-V Basic": notes/cs61c/4-RISC-V.md
          - "5 CALL": notes/cs61c/5-CALL.md
          - "6 Processor Design": notes/cs61c/6-processor-design.md
          - "7 Pipeline": notes/cs61c/7-pipeline.md
          - "8 Cache": notes/cs61c/8-cache.md
          - "9 Parallelism": notes/cs61c/9-parallelism.md
      - 6.s081:
          - "1 Intro": notes/6.s081/1-intro.md
      - SJTU 随机过程:
          - "Review of Probability": notes/stochastic-progress/Lecture0-Review-of-Probability.md
          - "Concentration Inequalities": notes/stochastic-progress/Lecture3-Concentration-Inequalities.md
          - "Markov Chains with Finite States": notes/stochastic-progress/Lecture4-Markov-Chains-with-Finite-States.md
          - "Coupling, Fundamental Theorem of Markov Chains": notes/stochastic-progress/Lecture5-Coupling-Fundamental-Theorem-of-Markov-Chains.md
          - "Mixing Time of Markov Chains": notes/stochastic-progress/Lecture6-Mixing-Time-of-Markov-Chains.md
          - "Chains with Infinite States": notes/stochastic-progress/Lecture7-Chains-with-Infinite-States.md
          - "Recurrence and Positive Recurrence": notes/stochastic-progress/Lecture8-Recurrence-and-Positive-Recurrence.md
          - "Fundamental Theorem of Markov Chains (General Version)": notes/stochastic-progress/Lecture9-Fundamental-Theorem-of-Markov-Chains-(General-Version).md
          - "Poisson Distribution, Poisson Processes": notes/stochastic-progress/Lecture10-Poisson-Distribution-Poisson-Processes.md
          - "Poisson Approximation": notes/stochastic-progress/Lecture12-Poisson-Approximation.md
          - "Conditional Expectation": notes/stochastic-progress/Lecture13-Conditional-Expectation.md
          - "Martingale": notes/stochastic-progress/Lecture14-Martingale.md
          - "Concentration with Martingale": notes/stochastic-progress/Lecture15-Concentration-with-Martingale.md
          - "Optional Stopping Theorem (OST)": notes/stochastic-progress/Lecture16-Optional-Stopping-Theorem.md
          - "Brownian Motion": notes/stochastic-progress/Lecture18-Brownian-Motion.md
          - "Informal Definition of Diffusion and Examples": notes/stochastic-progress/Lecture19-Informal-Definition-of-Diffusion-and-Examples.md
          - "Itô Integral, Itô Formula": notes/stochastic-progress/Lecture20-Itô-Integral-Itô-Formula.md
          - "Markov Semigroup": notes/stochastic-progress/Lecture21-Markov-Semigroup.md
          - "Kolmogorov Forward or Backward Equations": notes/stochastic-progress/Lecture22-Kolmogorov-Forward-or-Backward-Equations.md
          - "Convergence of Langevin Diffusion, DDPM": notes/stochastic-progress/Lecture23-Convergence-of-Langevin-Diffusion-DDPM.md
      - CSE234:
          - notes/cse234/lec2.md
      - 强化学习:
          - notes/RL/Stochastic-Approximation.md
          - notes/RL/Actor-Critic.md
          - notes/RL/Temporal-Difference-Learning.md
          - notes/RL/Value-Function-Approximation.md
          - notes/RL/Policy-Function-Approximation.md
          - notes/RL/Bellman-Optimal-Equation.md
          - notes/RL/Monte-Carlo-Learning.md
          - notes/RL/Value-or-Policy-Iteration.md
          - notes/RL/Dyna-Q.md
          - notes/RL/GAE.md
      - CS236:
          - notes/CS236/Autoregressive-Flow.md
          - notes/CS236/Autoregressive-Models.md
          - notes/CS236/Bayesian-networks.md
          - notes/CS236/Diffusion-Model.md
          - notes/CS236/Energy-Based-Model-(EBM).md
          - notes/CS236/Flow-Contrastive-Estimation.md
          - notes/CS236/Flow-Models.md
          - notes/CS236/Gaussian-Perturbation.md
          - notes/CS236/Gaussianization-Flows.md
          - notes/CS236/Latent-Variable-Models.md
          - notes/CS236/Maximum-Likelihood-Learning.md
          - notes/CS236/Noise-Contrastive-Estimation.md
          - notes/CS236/Nonlinear-Independent-Components-Estimation-(NICE).md
          - notes/CS236/Parallel-Wavenet.md
          - notes/CS236/Real-NVP.md
          - notes/CS236/Score-Matching.md
          - notes/CS236/Score-based-Model.md
          - notes/CS236/Summary.md
      - "SJTU Architecture":
          - notes/SJTU-architecture/Lecture3.md
  - Summaries:
      - index: summary/index.md
      - "2025":
          - "一周总结与回顾-3": summary/2025/summary-3.md
          - "一周总结与回顾-2": summary/2025/summary-2.md
          - "一周总结与回顾-1": summary/2025/summary-1.md
          - "大二下规划": summary/2025/semester-plan.md
      - "2024":
          - "一周总结与回顾-8": summary/2024/summary-8.md
          - "一周总结与回顾-7": summary/2024/summary-7.md
          - "一周总结与回顾-6": summary/2024/summary-6.md
          - "一周总结与回顾-5": summary/2024/summary-5.md
          - "一周总结与回顾-4": summary/2024/summary-4.md
          - "一周总结与回顾-3": summary/2024/summary-3.md
          - "一周总结与回顾-2": summary/2024/summary-2.md
  - Links: links/index.md
  - About: about/index.md
  - Blogs: https://kinnari-blog.vercel.app/
